//! OSC 133 shell integration.
//!
//! The block model depends on knowing exactly where a command starts and ends.
//! Guessing from prompt heuristics is unreliable, so we ship hook scripts that
//! make the shell announce those boundaries with OSC 133 semantic sequences:
//!
//! - `OSC 133 ; A ST` — prompt start
//! - `OSC 133 ; B ST` — command start (end of prompt)
//! - `OSC 133 ; C ST` — output start (command was submitted)
//! - `OSC 133 ; D ; <exit> ST` — command end, with exit code
//!
//! We additionally emit OSC 7 (`file://host/path`) so the UI can track cwd
//! without ever parsing the prompt.
//!
//! The scripts are written to the app's config dir on launch and sourced by the
//! user's rc file. Sessions where the hooks are absent — a remote host without
//! them installed — degrade to a single continuous block, which is the intended
//! behavior; a wrong boundary is worse than none.

use std::path::{Path, PathBuf};

use anyhow::Result;

pub const ZSH_HOOK: &str = r#"# TRMNL shell integration (zsh) — OSC 133 semantic prompts.
# Sourced automatically by TRMNL. Safe to source twice.
if [[ -n "$TRMNL_INTEGRATION_LOADED" ]]; then
  return 0
fi
TRMNL_INTEGRATION_LOADED=1

__trmnl_osc() { printf '\033]133;%s\a' "$1"; }

# Report cwd via OSC 7 so the UI never has to parse the prompt.
__trmnl_cwd() { printf '\033]7;file://%s%s\a' "$HOST" "$PWD"; }

# zsh marks output that lacks a trailing newline with a reverse-video '%', pads
# to the line width, then erases it with CR-space-CR. A cursor-addressed
# terminal wipes it; the block stream has no cursor, so the marker would survive
# as visible text. The block model already delimits output, so the mark is
# redundant here.
unsetopt PROMPT_SP 2>/dev/null
PROMPT_EOL_MARK=''

# Marks the end of output for the previous command, carrying its exit status.
__trmnl_precmd() {
  local ret=$?
  if [[ -n "$__trmnl_running" ]]; then
    __trmnl_osc "D;$ret"
    unset __trmnl_running
  fi
  __trmnl_cwd
  __trmnl_osc "A"
}

# Marks the transition from prompt to running command.
__trmnl_preexec() {
  __trmnl_running=1
  __trmnl_osc "C"
}

# `B` closes the prompt region; PS1 ends with it.
PS1="$PS1"$'%{\033]133;B\a%}'

autoload -Uz add-zsh-hook 2>/dev/null
if (( $+functions[add-zsh-hook] )); then
  add-zsh-hook precmd __trmnl_precmd
  add-zsh-hook preexec __trmnl_preexec
fi
"#;

pub const BASH_HOOK: &str = r#"# TRMNL shell integration (bash) — OSC 133 semantic prompts.
# Sourced automatically by TRMNL. Safe to source twice.
if [ -n "$TRMNL_INTEGRATION_LOADED" ]; then
  return 0
fi
TRMNL_INTEGRATION_LOADED=1

__trmnl_osc() { printf '\033]133;%s\a' "$1"; }
__trmnl_cwd() { printf '\033]7;file://%s%s\a' "${HOSTNAME:-localhost}" "$PWD"; }

# bash has no preexec, so DEBUG stands in for it. Guarded so it fires once per
# command rather than once per expression in a compound statement.
__trmnl_preexec() {
  [ -n "$COMP_LINE" ] && return
  [ "$BASH_COMMAND" = "$PROMPT_COMMAND" ] && return
  if [ -z "$__trmnl_running" ]; then
    __trmnl_running=1
    __trmnl_osc "C"
  fi
}

__trmnl_precmd() {
  local ret=$?
  if [ -n "$__trmnl_running" ]; then
    __trmnl_osc "D;$ret"
    unset __trmnl_running
  fi
  __trmnl_cwd
  __trmnl_osc "A"
}

trap '__trmnl_preexec' DEBUG
case "$PROMPT_COMMAND" in
  *__trmnl_precmd*) ;;
  "") PROMPT_COMMAND="__trmnl_precmd" ;;
  *) PROMPT_COMMAND="__trmnl_precmd;$PROMPT_COMMAND" ;;
esac

PS1="$PS1\[\033]133;B\a\]"
"#;

pub const FISH_HOOK: &str = r#"# TRMNL shell integration (fish) — OSC 133 semantic prompts.
# Sourced automatically by TRMNL. Safe to source twice.
if set -q TRMNL_INTEGRATION_LOADED
    exit 0
end
set -g TRMNL_INTEGRATION_LOADED 1

function __trmnl_osc
    printf '\033]133;%s\a' $argv[1]
end

function __trmnl_cwd
    printf '\033]7;file://%s%s\a' (hostname) $PWD
end

function __trmnl_preexec --on-event fish_preexec
    set -g __trmnl_running 1
    __trmnl_osc "C"
end

function __trmnl_postexec --on-event fish_postexec
    set -l ret $status
    if set -q __trmnl_running
        __trmnl_osc "D;$ret"
        set -e __trmnl_running
    end
end

function __trmnl_prompt --on-event fish_prompt
    __trmnl_cwd
    __trmnl_osc "A"
end
"#;

/// Write the hook scripts into `<config>/shell-integration/` and return that dir.
///
/// Rewritten on every launch so an upgraded TRMNL ships updated hooks without
/// the user having to do anything.
pub fn install(config_dir: &Path) -> Result<PathBuf> {
    let dir = config_dir.join("shell-integration");
    std::fs::create_dir_all(&dir)?;

    // bash is launched with `--rcfile`, which REPLACES the user's rc file rather
    // than adding to it, so the shim has to source theirs explicitly first.
    let bash_rc = format!(
        r#"# Generated by TRMNL. Do not edit — rewritten on every launch.
# Passed to bash via --rcfile, which replaces the default rc file, so the user's
# own config is sourced here before our hooks load.
for f in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do
  if [ -f "$f" ]; then . "$f"; break; fi
done
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"
. "{hook}"
"#,
        hook = dir.join("trmnl.bash").to_string_lossy(),
    );

    for (name, contents) in [
        ("trmnl.zsh", ZSH_HOOK),
        ("trmnl.bash", BASH_HOOK),
        ("trmnl.fish", FISH_HOOK),
        ("trmnl.bashrc", bash_rc.as_str()),
    ] {
        let path = dir.join(name);
        // Only rewrite when the content actually differs, so we don't churn
        // mtimes (and any file watchers) on every launch.
        let needs_write = match std::fs::read_to_string(&path) {
            Ok(existing) => existing != contents,
            Err(_) => true,
        };
        if needs_write {
            std::fs::write(&path, contents)?;
        }
    }

    Ok(dir)
}

/// The line a user adds to their rc file to enable integration.
pub fn source_line(dir: &Path, shell: &str) -> String {
    let file = match shell {
        "bash" => "trmnl.bash",
        "fish" => "trmnl.fish",
        _ => "trmnl.zsh",
    };
    let path = dir.join(file).to_string_lossy().to_string();
    if shell == "fish" {
        format!("test -f \"{path}\" && source \"{path}\"")
    } else {
        format!("[ -f \"{path}\" ] && . \"{path}\"")
    }
}
